package.json
Use "run less" to run the less watch compiler
=> Add less compiler script 

less/globals.less, less/landingPage.less, pages/index.jsx, styles/globals.css
-Just made a few quick styling tweaks to the landing page. 
-Will probably want it to be more elaborate later.
=> Style landing page according to wireframe

components/NavBar.jsx, components/UserProfileView.jsx, package.json, pages/user/homepage.jsx, styles/globals.css
User's profile page
- matches are displayed horizontally
- scroll view added for matches
- drop down card for each match which displays whole bio and enlarges when clicked
- added CSS to matches card on homepage and matches bio
=> Matches card animation

components/NavBar.jsx, components/UserProfileView.jsx, pages/index.jsx, pages/user/homepage.jsx
fixed <li> error on main page, couple console errors that didnt break anything. 
Not sure if styled components are used but it was causing a lot of issues even after I restarted my server.
If needed we can find a workaround
=> Housekeeping

components/EmailSignIn.jsx, components/OAuthBar.jsx, pages/login.jsx, store/reducers/matchesSlice.js, store/reducers/userSlice.js
oauth working for google
working buttons for github and facebook but needs supabase clientID update
login error handling updated
no matches bug on profile view frixed closes #21
=> Providerlogin

components/EmailSignIn.jsx, components/NavBar.jsx, components/OAuthBar.jsx, less/footer.less, less/form.less, less/globals.less, less/nav.less, less/oAuthBar.less, less/profile.less, package.json, pages/login.jsx, styles/globals.css
Move links into email sign in component and style with icons
=> Style Updates - See Comments

.gitignore, components/UserProfile.jsx, components/UserProfileEdit.jsx, components/UserProfileView.jsx, less/globals.less, less/profile.less, less/survey.less, pages/user/homepage.jsx, styles/globals.css
- styles/alignment for UserProfileEdit are well adjusted, still need to change colors and account for more preference fields
- UserProfileView is WIP still
=> styling and RWD for UserProfileEdit.jsx (and UserProfileView kind of)

components/EmailSignUp.jsx
=> OAuth in signup

components/NavBar.jsx, components/OAuthBar.jsx, components/UpdateUserAuth.jsx, less/form.less, less/globals.less, pages/user/setting.jsx, store/reducers/userSlice.js, styles/globals.css
=> Authupdate

components/NavBar.jsx, components/UpdateUserAuth.jsx, components/UserProfile.jsx, components/UserProfileEdit.jsx, components/UserProfileView.jsx, less/survey.less, styles/globals.css
decided not to make a dropdown component in the navbar so i could leave cory's burger menu setup in peace and not screw anything up by accident. i think the current setup is realistic though
=> user view/edit/update login are now all under 'account' tab in navbar

components/Opti/ActionProvider.jsx, components/Opti/MessageParser.jsx, less/profile.less, pages/user/homepage.jsx, styles/globals.css
- fixed bugs and made small changes
=> bugs and small changes

components/EmailSignIn.jsx, components/Matches.jsx, components/UserProfileEdit.jsx, components/UserProfileView.jsx, less/profile.less, styles/globals.css
-Use the button "update location" to change current user's latitude and longitude to mirror current device
-Matches now display distance in miles from each match
*Potential bug - refreshing the page causes all matches to display "NaN" for distance
=> Add location

components/Matches.jsx, components/UserProfileView.jsx, less/messenger.less, less/survey.less
-Change styles on pages
-Add successful updated location
=> Final style updates 1

components/UserProfileView.jsx, less/profile.less
Add a hover option to disclose to users what adding precise location actually does
=> Add precise location info

components/Opti/MessageParser.jsx, store/index.js, store/reducers/blacklistSlice.js
reported user is now logged into our blacklist table in supabase
=> reported user added to blacklist table

less/profile.less
=> scroll padding

components/Footer.jsx, less/profile.less
=> fixed up profile card

components/Footer.jsx, less/aboutUs.less, less/bot.less, less/faq.less, less/footer.less, pages/aboutUs.jsx, pages/faq.jsx
=> fixed links

less/bot.less
- botti fixed on mobile view !
=> Reported user

less/bot.less, less/faq.less, pages/help.jsx
css fixes on footer routes mobile view
=> css fixes on footer routes mobile view

components/NavBar.jsx, less/aboutUs.less, less/nav.less, pages/aboutUs.jsx
css changes to navbar and faq on mobile view
=> css changes to navbar and faq on mobile view

less/footer.less, less/nav.less
=> navbar css

less/aboutUs.less
more css changes on mobile view
=> more css changes on mobile view

less/aboutUs.less, less/bot.less, less/messenger.less
css changes to bot and aboutUs
=> css changes to bot and aboutUs

less/aboutUs.less
- adjusted about us size on desktop view
=> about us size adjustment
